# application.yml do API Gateway

server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # --- Rota para o shipping-service ---
        - id: shipping_route
          uri: http://shipping-service:8081
          predicates:
            - Path=/api/shipping/**
          filters:
            - StripPrefix=2

        # --- Rota para o order-service ---
        - id: order_route
          uri: http://order-service:8083
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2

        # --- Rota para o cart-service ---
        - id: cart_route
          uri: http://cart-service:8084
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=2

        # --- Rota para o book-service ---
        - id: book_route
          uri: http://book-service:8082
          predicates:
            - Path=/api/book/**
          filters:
            - StripPrefix=2

        # --- Rota para o user-service ---
        - id: user_route
          uri: http://user-service:8080
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    reactor.netty.http.client: INFO
    org.springframework.web: DEBUG
