server:
  port: 9000

book:
  service:
    url: http://localhost:8082

cart:
  service:
    url: http://localhost:8084

user:
  service:
    url: http://localhost:8080

order:
  service:
    url: http://localhost:8083


spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # --- Rota para o shipping-service ---
        - id: shipping_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/shipping/**
          filters:
            - StripPrefix=2

        # --- Rota para o order-service ---
        - id: order_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2

        # --- Rota para o cart-service ---
        - id: cart_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=2

        # --- Rota para o book-service ---
        - id: book_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/book/**
          filters:
            - StripPrefix=2

        # --- Rota para o user-service ---
        - id: user_route
          uri: http://localhost:8080
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
